# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\")\n\x07Numbers\x12\x0e\n\x06numOne\x18\x01 \x01(\x01\x12\x0e\n\x06numTwo\x18\x02 \x01(\x01\"(\n\x06Result\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x0f\n\x07message\x18\x02 \x01(\t2\x81\x01\n\nCalculator\x12\x18\n\x03\x41\x64\x64\x12\x08.Numbers\x1a\x07.Result\x12\x1d\n\x08Subtract\x12\x08.Numbers\x1a\x07.Result\x12\x1d\n\x08Multiply\x12\x08.Numbers\x1a\x07.Result\x12\x1b\n\x06\x44ivide\x12\x08.Numbers\x1a\x07.Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMBERS']._serialized_start=20
  _globals['_NUMBERS']._serialized_end=61
  _globals['_RESULT']._serialized_start=63
  _globals['_RESULT']._serialized_end=103
  _globals['_CALCULATOR']._serialized_start=106
  _globals['_CALCULATOR']._serialized_end=235
# @@protoc_insertion_point(module_scope)
